Landing page fb
BOLT-UBC/BOLT-website pull request #23
Opened 2024-10-22 23:24 UTC by Davooood90

Changes:
- Updated navbar options
- Updated folder icon to be svg and not a bunch of messy css
- Created landing page (schedule component, important links component, useful links component)

*not compatible with all screen sizes at the moment

![image](https://github.com/user-attachments/assets/87dbe722-e2d8-4322-945c-d668080ad84a)

2024-10-22 23:52 UTC, LeoShangTang commented on src/pages/first-byte-page/FirstBytePage.tsx
Lets just json for the links, but we can do that later. Looks good otherwise

2024-10-23 00:04 UTC, LeoShangTang requested changes

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Schedule.tsx
Tasks can be apart of a json file, but don't worry about that for now

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/FBTitle.css
> +    margin-bottom: 30px;
we can prolly change this to rem for larger pixel sizes

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/FBTitle.css
> +    font-size: 40px;
change to rem for font size

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Folder.css
> +    font-size: 24px;
change to rem for font size

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Folder.css
> +    font-size: 20px;
change to rem for font size

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Schedule.css
> +    padding-right: 15px;
change to rem for this padding

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Schedule.css
> +    margin: 0 10px;
change to rem for margin

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Schedule.css
> +    width: 15px;
change to rem

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Schedule.css
> +    margin: 10px 0;
change to rem

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Task.css
> +    margin: 10px auto;
change to rem

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Task.css
> +    margin-bottom: 15px;
change to rem

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Task.css
> +    font-size: 20px;
change to rem

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Task.css
> +    font-size: 15px;
change to rem

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/UsefulLinks.css
> +    font-size: 15px;
change to rem

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Window.css
>      font-size: 18px;
change to rem

2024-10-23 00:04 UTC, LeoShangTang commented on src/pages/first-byte-page/styles.css
> +    padding-top: 63.5px;
change to rem

2024-10-23 00:15 UTC, Davooood90 commented on src/pages/first-byte-page/components/Folder.css
>  .fb-folder, .fb-folder-shadow {
Oh LOL I completely forgot about those comments. Its cause I pretty much redid the folder css completely since i switched to using an svg :p

2024-10-23 06:15 UTC, LeoShangTang commented on src/pages/first-byte-page/components/Window.css
> +    padding: 0.3rem 1rem;
btw a quick note is that 1rem = 16px

But if it looks fine or it was intentional to make the padding different, then looks good to me

2024-10-23 06:15 UTC, LeoShangTang approved these changes

2024-10-24 04:36 UTC, angelafeliciaa approved these changes

2024-10-24 04:44 UTC, andrewahn-ubc approved these changes

2024-10-24 05:49 UTC, merged